# Generated by Django 5.1.7 on 2025-04-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0002_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_cartao',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_dinheiro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
